image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    before: mvn clean package -DskipTests
    command: mvn spring-boot:run
  - name: Postgres Status Check
    command: pg_ctl status
  - name: Postgres CLI
    before: psql -h localhost -d postgres
    command: >
     \c postgres 
     DROP TABLE IF EXISTS cities;
     CREATE TABLE cities(id serial PRIMARY KEY, name VARCHAR(255), population integer);
     INSERT INTO cities(name, population) VALUES('Bratislava', 432000);
     INSERT INTO cities(name, population) VALUES('Budapest', 1759000);
     INSERT INTO cities(name, population) VALUES('Prague', 1280000);
     INSERT INTO cities(name, population) VALUES('Warsaw', 1748000);
     INSERT INTO cities(name, population) VALUES('Los Angeles', 3971000);
     INSERT INTO cities(name, population) VALUES('New York', 8550000);
     INSERT INTO cities(name, population) VALUES('Edinburgh', 464000);
     INSERT INTO cities(name, population) VALUES('Berlin', 3671000);
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
