image:
  file: .gitpod.Dockerfile

tasks:
  - name: Spring Boot Run
    init: mvn clean package -DskipTests
    before: 
      mvn spring-boot:run

  - name: Redis Server
    command: redis-server

  # - name: Redis CLI
  #   command: redis-cli

  # - name: Postgres Status Check
  #   command: pg_ctl status

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
