image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    before: mvn clean package

  - name: Postgres CLI
    before: psql -h localhost -d postgres
    command: pg_ctl status
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
