image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    before: mvn clean package -DskipTests
    command: mvn spring-boot:run
  # - name: Postgres Status Check
  #   command: pg_ctl status
  - name: Postgres CLI
    before: psql
    command: >
     \c postgres
     \i src/main/resources/schema-postgres.sql 
     \i src/main/resources/data-postgres.sql
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
