image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    init: mvn clean package -DskipTests
    before: 
      mvn spring-boot:run
    command: >
      cd src/main/resources
      ./run-postgres.sh
  - name: Postgres Status Check
    command: pg_ctl status
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
