image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    before: mvn clean package

  # - name: Spring Boot
  #   command: ./mvnw spring-boot:run


    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
