image:
  file: .gitpod.Dockerfile

tasks:
  - name: Postgres Docker
    before: |
      docker run -it gitpod-dockerfile-test bash
      psql -h localhost -d postgres

  - name: Maven
    before: mvn install

  - name: Spring Boot
    command: mvn package ./mvnw spring-boot:run


    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
