image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven
    before: mvn clean package -DskipTests
    command: mvn spring-boot:run
  # - name: Postgres Status Check
  #   command: pg_ctl status
  - name: Postgres CLI
    command: cd src/main/resources && ./run-postgres.sh
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
