##for gitpod.io, apparently will get unauthorized from rest client extension, use embedded browser in gitpod.io instead

@hostname = https://8080-vanaraen111-gitpodiospr-aw0gfwdoyry.ws-us100.gitpod.io/city-api/
##change accordingly to current gitpod instance, refer to PORTS tab
@cityapi = api/cities


### View All Cities
GET {{hostname}}/{{cityapi}}

### Get City By Id
GET {{hostname}}/{{cityapi}}/3

